name: Deploy Azure Web App

on:
  push:
    branches:
     - main


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Setup Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install Dependencies
        run: npm install
      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: ets-web-ingrid
          publish-profile: ${{secrets.AZURE_PUBLISH_PROFILE}}
          package: .